apiVersion: v1
kind: Secret
metadata:
  name: alertservice-secret
type: Opaque
data:
  SECRET_KEY: YWxlcnRfc2VydmljZV9zZWNyZXQ=  # base64 encoded "alert_service_secret"
  POSTGRES_PASSWORD: YWxlcnRwYXNz  # base64 encoded "alertpass"